import type { Metadata } from 'next'
import { Jura } from 'next/font/google'
import './globals.css'

const bodyFont = Jura({
    variable: '--font-body',
    subsets: ['cyrillic', 'latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${bodyFont.variable} font-body antialiased`}>
                <main>{children}</main>
            </body>
        </html>
    )
}
